config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers
  end

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  expose(:questions)
  expose(:question)

  def index
  end

  def show
  end

  def new
  end

  def create
    self.question = Question.new(question_params)
    if question.save
      redirect_to question, notice: 'Question added successfully'
    else
      render action: 'new'
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :content)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title StarkOverflow
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header
      nav.navbar
        .container
          .navbar-header
            .logo.pull-left
              | STARK
              b OVERFLOW
            .pull-right
              | Zaloguj
              | Zarejestruj

    .container
      = yield

app/views/questions/_form.html.slim
= simple_form_for(question, html: { class: 'form-horizontal' }) do |f|
  = f.input :title
  = f.input :content
  = f.submit 'Create', class: 'btn btn-primary'
end

app/views/questions/_question.html.slim
.col-md-12
  = link_to "#{question.title}", question

app/views/questions/index.html.slim
.container
  .col-md-8
    h1 Topics
    = render(questions) || "There are no questions yet."

    = link_to 'New Question', new_question_path, class: 'btn btn-primary'
  .col-md-4
    | well z tagami

app/views/questions/new.html.slim
h1 Add new Question
= render 'form'

app/views/questions/show.html.slim
= question.title
= question.content